---

- name: Install openssl
  package:
    name: openssl
    state: present

- name: Import Remote Certificates
  with_items: "{{ cacerts | default ([]) }}"
  when:
    - cacerts is defined
    - cacerts_cert.location is defined
  loop_control:
    loop_var: cacerts_cert
  include: "{{ cacerts_cert.location }}.yml"
  static: false
